// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumCalculationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          int32                  `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          int32                  `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumCalculationRequest) Reset() {
	*x = SumCalculationRequest{}
	mi := &file_sum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumCalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumCalculationRequest) ProtoMessage() {}

func (x *SumCalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumCalculationRequest.ProtoReflect.Descriptor instead.
func (*SumCalculationRequest) Descriptor() ([]byte, []int) {
	return file_sum_proto_rawDescGZIP(), []int{0}
}

func (x *SumCalculationRequest) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *SumCalculationRequest) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type SumCalculationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumCalculationResponse) Reset() {
	*x = SumCalculationResponse{}
	mi := &file_sum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumCalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumCalculationResponse) ProtoMessage() {}

func (x *SumCalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumCalculationResponse.ProtoReflect.Descriptor instead.
func (*SumCalculationResponse) Descriptor() ([]byte, []int) {
	return file_sum_proto_rawDescGZIP(), []int{1}
}

func (x *SumCalculationResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_sum_proto protoreflect.FileDescriptor

const file_sum_proto_rawDesc = "" +
	"\n" +
	"\tsum.proto\x12\x03sum\"?\n" +
	"\x15SumCalculationRequest\x12\x12\n" +
	"\x04num1\x18\x01 \x01(\x05R\x04num1\x12\x12\n" +
	"\x04num2\x18\x02 \x01(\x05R\x04num2\"0\n" +
	"\x16SumCalculationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2T\n" +
	"\aSumCalc\x12I\n" +
	"\x0eSumCalculation\x12\x1a.sum.SumCalculationRequest\x1a\x1b.sum.SumCalculationResponseB\x1cZ\x1aexample.com/exercise/protob\x06proto3"

var (
	file_sum_proto_rawDescOnce sync.Once
	file_sum_proto_rawDescData []byte
)

func file_sum_proto_rawDescGZIP() []byte {
	file_sum_proto_rawDescOnce.Do(func() {
		file_sum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sum_proto_rawDesc), len(file_sum_proto_rawDesc)))
	})
	return file_sum_proto_rawDescData
}

var file_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sum_proto_goTypes = []any{
	(*SumCalculationRequest)(nil),  // 0: sum.SumCalculationRequest
	(*SumCalculationResponse)(nil), // 1: sum.SumCalculationResponse
}
var file_sum_proto_depIdxs = []int32{
	0, // 0: sum.SumCalc.SumCalculation:input_type -> sum.SumCalculationRequest
	1, // 1: sum.SumCalc.SumCalculation:output_type -> sum.SumCalculationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sum_proto_init() }
func file_sum_proto_init() {
	if File_sum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sum_proto_rawDesc), len(file_sum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sum_proto_goTypes,
		DependencyIndexes: file_sum_proto_depIdxs,
		MessageInfos:      file_sum_proto_msgTypes,
	}.Build()
	File_sum_proto = out.File
	file_sum_proto_goTypes = nil
	file_sum_proto_depIdxs = nil
}
