package main

import (
	"log"
	"net"

	// pb is an alias for the package generated by `protoc` from greet.proto.
	// Import path = `module` line in go.mod ("example.com/greet") + folder
	// path to the .pb.go files ("/proto").
	// We alias it as `pb` so the call sites read like pb.GreetRequest, and
	// to avoid collisions with google.golang.org/protobuf/proto.
	pb "example.com/greet/proto"
	"google.golang.org/grpc"
)

// 0.0.0.0 means "listen on every network interface on this machine".
// 50051 is the conventional port used in gRPC examples; it's not special.
var addr = "0.0.0.0:50051"

// Server is our concrete implementation of the GreetService.
//
// Embedding pb.UnimplementedGreetServiceServer is REQUIRED:
//  1. It satisfies the unexported `mustEmbedUnimplementedGreetServiceServer()`
//     method on the GreetServiceServer interface, so this struct is a valid
//     server type.
//  2. It provides default "Unimplemented" stubs for every RPC. If we add a
//     new RPC to greet.proto later, this server still compiles — the new
//     method just returns codes.Unimplemented until we override it.
type Server struct {
	pb.UnimplementedGreetServiceServer
}

func main() {
	// Step 1: open a TCP socket. gRPC speaks HTTP/2 over TCP, so we need a
	// raw net.Listener that the gRPC runtime can accept connections from.
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		log.Fatalf("Failed to listen on %s: %v", addr, err)
	}
	log.Printf("Listening on %s", addr)

	// Step 2: create the gRPC runtime. This object knows how to read HTTP/2
	// frames, decode protobuf, and dispatch incoming RPCs to handlers.
	// At this point it has no services registered yet.
	s := grpc.NewServer()

	// Step 3: wire our Server implementation to the GreetService descriptor.
	// Under the hood this registers the service name "greet.GreetService"
	// and its method table, so when a request comes in for
	// "/greet.GreetService/Greet" the runtime knows to call our struct.
	pb.RegisterGreetServiceServer(s, &Server{})

	// Step 4: start accepting connections. Serve blocks until the server is
	// stopped or the listener errors out, so this is effectively the end of
	// main().
	if err := s.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v", err)
	}
}
