// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: exercise.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DivisorFinder_FindDivisors_FullMethodName = "/exercise.DivisorFinder/FindDivisors"
)

// DivisorFinderClient is the client API for DivisorFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DivisorFinderClient interface {
	
	FindDivisors(ctx context.Context, in *DivisorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DivisorResponse], error)
}

type divisorFinderClient struct {
	cc grpc.ClientConnInterface
}

func NewDivisorFinderClient(cc grpc.ClientConnInterface) DivisorFinderClient {
	return &divisorFinderClient{cc}
}

func (c *divisorFinderClient) FindDivisors(ctx context.Context, in *DivisorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DivisorResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DivisorFinder_ServiceDesc.Streams[0], DivisorFinder_FindDivisors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DivisorRequest, DivisorResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DivisorFinder_FindDivisorsClient = grpc.ServerStreamingClient[DivisorResponse]

// DivisorFinderServer is the server API for DivisorFinder service.
// All implementations must embed UnimplementedDivisorFinderServer
// for forward compatibility.
type DivisorFinderServer interface {
	FindDivisors(*DivisorRequest, grpc.ServerStreamingServer[DivisorResponse]) error
	mustEmbedUnimplementedDivisorFinderServer()
}

// UnimplementedDivisorFinderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDivisorFinderServer struct{}

func (UnimplementedDivisorFinderServer) FindDivisors(*DivisorRequest, grpc.ServerStreamingServer[DivisorResponse]) error {
	return status.Error(codes.Unimplemented, "method FindDivisors not implemented")
}
func (UnimplementedDivisorFinderServer) mustEmbedUnimplementedDivisorFinderServer() {}
func (UnimplementedDivisorFinderServer) testEmbeddedByValue()                       {}

// UnsafeDivisorFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DivisorFinderServer will
// result in compilation errors.
type UnsafeDivisorFinderServer interface {
	mustEmbedUnimplementedDivisorFinderServer()
}

func RegisterDivisorFinderServer(s grpc.ServiceRegistrar, srv DivisorFinderServer) {
	// If the following call panics, it indicates UnimplementedDivisorFinderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DivisorFinder_ServiceDesc, srv)
}

func _DivisorFinder_FindDivisors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DivisorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DivisorFinderServer).FindDivisors(m, &grpc.GenericServerStream[DivisorRequest, DivisorResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DivisorFinder_FindDivisorsServer = grpc.ServerStreamingServer[DivisorResponse]

// DivisorFinder_ServiceDesc is the grpc.ServiceDesc for DivisorFinder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DivisorFinder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exercise.DivisorFinder",
	HandlerType: (*DivisorFinderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindDivisors",
			Handler:       _DivisorFinder_FindDivisors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "exercise.proto",
}
