// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: exercise.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DivisorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivisorRequest) Reset() {
	*x = DivisorRequest{}
	mi := &file_exercise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivisorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivisorRequest) ProtoMessage() {}

func (x *DivisorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivisorRequest.ProtoReflect.Descriptor instead.
func (*DivisorRequest) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{0}
}

func (x *DivisorRequest) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DivisorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        uint32                 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivisorResponse) Reset() {
	*x = DivisorResponse{}
	mi := &file_exercise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivisorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivisorResponse) ProtoMessage() {}

func (x *DivisorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivisorResponse.ProtoReflect.Descriptor instead.
func (*DivisorResponse) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{1}
}

func (x *DivisorResponse) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_exercise_proto protoreflect.FileDescriptor

const file_exercise_proto_rawDesc = "" +
	"\n" +
	"\x0eexercise.proto\x12\bexercise\"\"\n" +
	"\x0eDivisorRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\")\n" +
	"\x0fDivisorResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\rR\x06result2V\n" +
	"\rDivisorFinder\x12E\n" +
	"\fFindDivisors\x12\x18.exercise.DivisorRequest\x1a\x19.exercise.DivisorResponse0\x01B\x1cZ\x1aexample.com/exercise/protob\x06proto3"

var (
	file_exercise_proto_rawDescOnce sync.Once
	file_exercise_proto_rawDescData []byte
)

func file_exercise_proto_rawDescGZIP() []byte {
	file_exercise_proto_rawDescOnce.Do(func() {
		file_exercise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)))
	})
	return file_exercise_proto_rawDescData
}

var file_exercise_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exercise_proto_goTypes = []any{
	(*DivisorRequest)(nil),  // 0: exercise.DivisorRequest
	(*DivisorResponse)(nil), // 1: exercise.DivisorResponse
}
var file_exercise_proto_depIdxs = []int32{
	0, // 0: exercise.DivisorFinder.FindDivisors:input_type -> exercise.DivisorRequest
	1, // 1: exercise.DivisorFinder.FindDivisors:output_type -> exercise.DivisorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exercise_proto_init() }
func file_exercise_proto_init() {
	if File_exercise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exercise_proto_goTypes,
		DependencyIndexes: file_exercise_proto_depIdxs,
		MessageInfos:      file_exercise_proto_msgTypes,
	}.Build()
	File_exercise_proto = out.File
	file_exercise_proto_goTypes = nil
	file_exercise_proto_depIdxs = nil
}
