// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: bideirectionalStreams.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_bideirectionalStreams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bideirectionalStreams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_bideirectionalStreams_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_bideirectionalStreams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bideirectionalStreams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_bideirectionalStreams_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_bideirectionalStreams_proto protoreflect.FileDescriptor

const file_bideirectionalStreams_proto_rawDesc = "" +
	"\n" +
	"\x1bbideirectionalStreams.proto\x12\rbidirectional\"-\n" +
	"\fGreetRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\"'\n" +
	"\rGreetResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2^\n" +
	"\fGreetService\x12N\n" +
	"\rGreetEveryone\x12\x1b.bidirectional.GreetRequest\x1a\x1c.bidirectional.GreetResponse(\x010\x01B!Z\x1fexample.com/bidirectional/protob\x06proto3"

var (
	file_bideirectionalStreams_proto_rawDescOnce sync.Once
	file_bideirectionalStreams_proto_rawDescData []byte
)

func file_bideirectionalStreams_proto_rawDescGZIP() []byte {
	file_bideirectionalStreams_proto_rawDescOnce.Do(func() {
		file_bideirectionalStreams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bideirectionalStreams_proto_rawDesc), len(file_bideirectionalStreams_proto_rawDesc)))
	})
	return file_bideirectionalStreams_proto_rawDescData
}

var file_bideirectionalStreams_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bideirectionalStreams_proto_goTypes = []any{
	(*GreetRequest)(nil),  // 0: bidirectional.GreetRequest
	(*GreetResponse)(nil), // 1: bidirectional.GreetResponse
}
var file_bideirectionalStreams_proto_depIdxs = []int32{
	0, // 0: bidirectional.GreetService.GreetEveryone:input_type -> bidirectional.GreetRequest
	1, // 1: bidirectional.GreetService.GreetEveryone:output_type -> bidirectional.GreetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bideirectionalStreams_proto_init() }
func file_bideirectionalStreams_proto_init() {
	if File_bideirectionalStreams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bideirectionalStreams_proto_rawDesc), len(file_bideirectionalStreams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bideirectionalStreams_proto_goTypes,
		DependencyIndexes: file_bideirectionalStreams_proto_depIdxs,
		MessageInfos:      file_bideirectionalStreams_proto_msgTypes,
	}.Build()
	File_bideirectionalStreams_proto = out.File
	file_bideirectionalStreams_proto_goTypes = nil
	file_bideirectionalStreams_proto_depIdxs = nil
}
