// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: sum.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SumCalc_SumCalculation_FullMethodName = "/sum.SumCalc/SumCalculation"
)

// SumCalcClient is the client API for SumCalc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SumCalcClient interface {
	SumCalculation(ctx context.Context, in *SumCalculationRequest, opts ...grpc.CallOption) (*SumCalculationResponse, error)
}

type sumCalcClient struct {
	cc grpc.ClientConnInterface
}

func NewSumCalcClient(cc grpc.ClientConnInterface) SumCalcClient {
	return &sumCalcClient{cc}
}

func (c *sumCalcClient) SumCalculation(ctx context.Context, in *SumCalculationRequest, opts ...grpc.CallOption) (*SumCalculationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumCalculationResponse)
	err := c.cc.Invoke(ctx, SumCalc_SumCalculation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumCalcServer is the server API for SumCalc service.
// All implementations must embed UnimplementedSumCalcServer
// for forward compatibility.
type SumCalcServer interface {
	SumCalculation(context.Context, *SumCalculationRequest) (*SumCalculationResponse, error)
	mustEmbedUnimplementedSumCalcServer()
}

// UnimplementedSumCalcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSumCalcServer struct{}

func (UnimplementedSumCalcServer) SumCalculation(context.Context, *SumCalculationRequest) (*SumCalculationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SumCalculation not implemented")
}
func (UnimplementedSumCalcServer) mustEmbedUnimplementedSumCalcServer() {}
func (UnimplementedSumCalcServer) testEmbeddedByValue()                 {}

// UnsafeSumCalcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SumCalcServer will
// result in compilation errors.
type UnsafeSumCalcServer interface {
	mustEmbedUnimplementedSumCalcServer()
}

func RegisterSumCalcServer(s grpc.ServiceRegistrar, srv SumCalcServer) {
	// If the following call panics, it indicates UnimplementedSumCalcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SumCalc_ServiceDesc, srv)
}

func _SumCalc_SumCalculation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumCalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumCalcServer).SumCalculation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SumCalc_SumCalculation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumCalcServer).SumCalculation(ctx, req.(*SumCalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SumCalc_ServiceDesc is the grpc.ServiceDesc for SumCalc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SumCalc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sum.SumCalc",
	HandlerType: (*SumCalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SumCalculation",
			Handler:    _SumCalc_SumCalculation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sum.proto",
}
